repos:
  - repo: local
    hooks:
      - id: lint-ui
        name: Lint UI
        entry: bash -c 'cd ui && npm run lint'
        language: system
        files: '\.(js|jsx|ts|tsx)$'
        exclude: "^ui/node_modules/"
        always_run: true
        pass_filenames: false
        args: []
        stages: [commit]
        additional_dependencies: []
        description: This hook lints the UI with ESLint.

      - id: test-ui
        name: Test UI
        entry: bash -c 'cd ui && npm run test -- --watchAll=false'
        language: system
        files: '\.(js|jsx|ts|tsx)$'
        exclude: "^ui/node_modules/"
        always_run: true
        pass_filenames: false
        args: []
        stages: [commit]
        additional_dependencies: []
        description: This hook runs the tests for the UI with Jest.

      - id: lint-continuum
        name: Lint Continuum
        entry: python3.10 -m flake8 ./continuum
        language: system
        files: '\.(py)$'
        always_run: true
        pass_filenames: false
        args: []
        stages: [commit]
        additional_dependencies: []
        description: This hook lints the Continuum backend with flake8.

      - id: format-continuum
        name: Format Continuum
        entry: python3.10 -m black --check --line-length 120 .
        language: system
        files: '\.(py)$'
        always_run: true
        pass_filenames: false
        args: []
        stages: [commit]
        additional_dependencies: []
        description: This hook formats the Continuum backend with black.

      - id: test-continuum
        name: Test Continuum
        entry: ./continuum/run_tests.sh
        language: script
        files: '\.(py)$'
        always_run: true
        pass_filenames: false
        stages: [commit]
        additional_dependencies: []
        description: This hook runs Django tests.
