# Generated by Django 4.2.4 on 2024-04-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thought", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thought",
            name="actions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="thought",
            name="mood",
            field=models.IntegerField(
                choices=[(1, "Very Unhappy"), (2, "Unhappy"), (3, "Neutral"), (4, "Happy"), (5, "Very Happy")],
                null=True,
            ),
        ),
    ]
