name: Build and Deploy Continuum to ECR

on:
  push:
    branches:
      - main
    # paths:
    #   - "continuum/**"
  pull_request:
    branches:
      - main
    paths:
      - "continuum/**"

jobs:
  build-continuum:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Docker Environment
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker Image to ECR
        run: |
          docker build -f ./continuum/Dockerfile.prod -t 664735937512.dkr.ecr.eu-west-2.amazonaws.com/continuum:latest ./continuum
          docker push 664735937512.dkr.ecr.eu-west-2.amazonaws.com/continuum:latest
